[package]
name = "versionsbot"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "versionsbot"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"

[dependencies]
teloxide = { version = "0.13", features = ["macros", "throttle"] }
tokio = { version = "1", features = ["full"] }
sea-orm = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
sea-orm-migration = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
anyhow = "1"
thiserror = "1"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
serde_json = "1"